/*
 * ShareButton.tsx
 *
 * This file exports the ShareButton component — the "Del med lærer" (Share with teacher)
 * button and its associated modal that students use to send a copy of their chat session
 * to their teacher.
 *
 * Exports:
 *   - default: ShareButton (React functional component)
 *
 * How it fits in the app:
 *   ShareButton is rendered in the student chat header. When clicked it opens a modal
 *   that automatically calls /api/generate-report to produce a plain-text summary of the
 *   conversation. The student can preview the report and then click "Send til lærer" to
 *   dispatch it via /api/send-report, which forwards the report to the teacher by email
 *   using the Resend service. The button is disabled when no messages exist yet.
 */

// Marks this as a client component so it can handle click events and manage its own state.
'use client'

// Imports hooks: useState for component state, useEffect to trigger side effects (report generation).
import { useState, useEffect } from 'react'

/*
 * Message is a TypeScript interface that defines the shape of a single chat message
 * as used by this component. Only the fields needed for report generation are included:
 *   - role: either 'user' (student) or 'assistant' (ThinkBot AI)
 *   - content: the text body of the message (string)
 */
// Minimal message shape used here — only role and content are needed to generate the report.
interface Message {
  role: 'user' | 'assistant'
  content: string
}

/*
 * ShareButtonProps is a TypeScript interface that defines the shape of the props object
 * accepted by the ShareButton component. It requires:
 *   - messages: an array of Message objects representing the full conversation history
 *   - masterprompt: a string containing the teacher's configured masterprompt, included
 *     in the report so the teacher has full context when reviewing the student's session
 */
// Props required by the ShareButton component.
interface ShareButtonProps {
  messages: Message[] // The full conversation history to include in the report.
  masterprompt: string // The teacher's configured masterprompt, included in the report for context.
}

/*
 * ShareButton is a function that takes 1 parameter
 *   ({ messages, masterprompt }: ShareButtonProps)
 * and returns JSX (a React element).
 *
 * It renders a trigger button and, when the modal is open, the full share modal. State
 * variables control every phase of the flow: opening the modal, generating the report,
 * displaying it, sending it, and showing success or error feedback.
 */
// The "Del med lærer" button and its associated modal for previewing and sending the chat report.
export default function ShareButton({ messages, masterprompt }: ShareButtonProps) {
  // open is a boolean state variable — controls whether the share modal is visible.
  const [open, setOpen] = useState(false)
  // transcript is a string state variable — holds the generated plain-text report shown in the preview area.
  const [transcript, setTranscript] = useState('')
  // loading is a boolean state variable — true while the email send request is in flight.
  const [loading, setLoading] = useState(false)
  // generating is a boolean state variable — true while the report is being generated by the API.
  const [generating, setGenerating] = useState(false)
  // sent is a boolean state variable — true after the email is successfully sent, triggering a confirmation message.
  const [sent, setSent] = useState(false)
  // error is a string state variable — holds any error message to display in the modal. Empty string means no error.
  const [error, setError] = useState('')

  /*
   * This useEffect runs whenever open, messages, or masterprompt changes. It handles
   * automatic report generation as soon as the modal opens:
   *   1. If the modal is closed (open === false), return early and do nothing.
   *   2. Set generating to true to show the spinner.
   *   3. POST the messages and masterprompt to /api/generate-report.
   *   4. On success, store the returned plain-text report in the transcript state.
   *   5. On failure, store a Danish error message in the error state.
   *   6. Always set generating back to false when done.
   */
  // Automatically generates the report when the modal opens by calling the /api/generate-report endpoint.
  useEffect(() => {
    if (!open) return // Do nothing while the modal is closed.
    setGenerating(true)
    setError('')
    setSent(false)

    // Sends the conversation and masterprompt to the server to generate a plain-text report.
    fetch('/api/generate-report', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ messages, masterprompt }),
    })
      .then((res) => {
        if (!res.ok) throw new Error('Report generation failed')
        return res.text() // The API returns plain text, not JSON.
      })
      .then((text) => setTranscript(text)) // Stores the generated report in state to display in the preview textarea.
      .catch(() => setError('Kunne ikke generere rapport. Prøv igen.'))
      .finally(() => setGenerating(false))
  }, [open, messages, masterprompt]) // Re-runs whenever the modal is opened or the messages change.

  /*
   * handleSend is a function that takes 0 parameters and returns Promise<void>.
   *
   * It is called when the student clicks "Send til lærer". Steps:
   *   1. Clear any existing error and set loading to true.
   *   2. POST the subject line and the generated transcript to /api/send-report.
   *   3. On success, set sent to true (shows confirmation) and schedule the modal to
   *      close automatically after 2 seconds.
   *   4. On failure, show a Danish error message.
   *   5. Always set loading back to false when done.
   */
  // Called when the user clicks "Send til lærer" — sends the generated report to the teacher via email.
  async function handleSend() {
    setError('')
    setLoading(true)

    try {
      // Posts the report to /api/send-report which forwards it to the teacher's email via Resend.
      const res = await fetch('/api/send-report', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          subject: 'ThinkBot Samtaleeksport',
          body: transcript, // The generated plain-text report.
        }),
      })

      if (!res.ok) throw new Error('Send failed')

      setSent(true) // Shows the "Email sendt" confirmation message.
      // Automatically closes the modal 2 seconds after a successful send.
      setTimeout(() => {
        setOpen(false)
        setSent(false)
      }, 2000)
    } catch {
      setError('Kunne ikke sende email. Prøv igen.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <>
      {/* The trigger button shown in the chat header. Disabled if there are no messages yet. */}
      <button
        onClick={() => setOpen(true)}
        disabled={messages.length === 0}
        className="px-4 py-2 rounded-lg text-sm font-medium border border-[var(--border)] text-gray-600 dark:text-gray-400 hover:bg-[var(--bg-panel)] transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
      >
        Del med lærer
      </button>

      {/* The share modal — only rendered when open is true. */}
      {open && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40">
          <div className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-xl shadow-xl w-full max-w-2xl mx-4 flex flex-col max-h-[80vh]">
            {/* Modal header with title and close button. */}
            <div className="flex items-center justify-between px-5 py-4 border-b border-[var(--border)]">
              <h2 className="text-lg font-semibold text-gray-800 dark:text-gray-200">
                Del samtale med lærer
              </h2>
              <button
                onClick={() => setOpen(false)}
                className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 text-xl leading-none"
              >
                ✕
              </button>
            </div>

            {/* Modal body — shows a spinner while generating, then the report preview textarea. */}
            <div className="flex-1 overflow-hidden px-5 py-4 flex flex-col gap-3">
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Forhåndsvisning af det der sendes til din lærer.
              </p>

              {generating ? (
                // Spinning loader shown while the API generates the report.
                <div className="flex-1 flex items-center justify-center py-12">
                  <svg
                    className="animate-spin h-6 w-6 text-gray-400"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                  >
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                  </svg>
                  <span className="ml-3 text-sm text-gray-500">Genererer rapport…</span>
                </div>
              ) : (
                // Read-only preview of the report text. The student can scroll it but not edit it.
                <textarea
                  value={transcript}
                  readOnly
                  className="flex-1 min-h-[300px] w-full rounded-lg border border-[var(--border)] bg-gray-50 dark:bg-gray-800 text-sm text-gray-800 dark:text-gray-200 p-3 resize-none focus:outline-none cursor-default"
                />
              )}

              {/* Error message shown if generation or sending failed. */}
              {error && (
                <p className="text-sm text-red-500">{error}</p>
              )}

              {/* Success confirmation shown briefly after the email is sent. */}
              {sent && (
                <p className="text-sm text-green-600 dark:text-green-400">
                  Email sendt til din lærer!
                </p>
              )}
            </div>

            {/* Modal footer with cancel and send buttons. */}
            <div className="flex items-center justify-end gap-3 px-5 py-4 border-t border-[var(--border)]">
              <button
                onClick={() => setOpen(false)}
                className="px-4 py-2 rounded-lg text-sm font-medium border border-[var(--border)] text-gray-600 dark:text-gray-400 hover:bg-[var(--bg-panel)] transition-colors"
              >
                Annuller
              </button>
              {/* Send button — disabled while generating, loading, if there's nothing to send, or after a successful send. */}
              <button
                onClick={handleSend}
                disabled={loading || generating || !transcript.trim() || sent}
                className="px-4 py-2 rounded-lg text-sm font-medium bg-blue-600 text-white hover:bg-blue-700 transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
              >
                {loading ? (
                  // Shows a spinner and "Sender…" text while the email request is in flight.
                  <span className="flex items-center gap-2">
                    <svg
                      className="animate-spin h-3.5 w-3.5"
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                    >
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                    </svg>
                    Sender…
                  </span>
                ) : (
                  'Send til lærer'
                )}
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  )
}
