// Marks this as a client component so it can handle click events and manage its own state.
'use client'

// Imports hooks: useState for component state, useEffect to trigger side effects (report generation).
import { useState, useEffect } from 'react'
import { useLanguage } from '@/lib/LanguageContext'

// Minimal message shape used here — only role and content are needed to generate the report.
interface Message {
  role: 'user' | 'assistant'
  content: string
}

// Props required by the ShareButton component.
interface ShareButtonProps {
  messages: Message[] // The full conversation history to include in the report.
  masterprompt: string // The teacher's configured masterprompt, included in the report for context.
}

// The "Del med lærer" button and its associated modal for previewing and sending the chat report.
export default function ShareButton({ messages, masterprompt }: ShareButtonProps) {
  const { t } = useLanguage()
  const [open, setOpen] = useState(false) // Controls whether the share modal is visible.
  const [transcript, setTranscript] = useState('') // Holds the generated plain-text report shown in the preview area.
  const [loading, setLoading] = useState(false) // True while the email send request is in flight.
  const [generating, setGenerating] = useState(false) // True while the report is being generated by the API.
  const [sent, setSent] = useState(false) // True after the email is successfully sent — shows a confirmation message.
  const [error, setError] = useState('') // Holds any error message to display in the modal.

  // Automatically generates the report when the modal opens by calling the /api/generate-report endpoint.
  useEffect(() => {
    if (!open) return // Do nothing while the modal is closed.
    setGenerating(true)
    setError('')
    setSent(false)

    // Sends the conversation and masterprompt to the server to generate a plain-text report.
    fetch('/api/generate-report', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ messages, masterprompt }),
    })
      .then((res) => {
        if (!res.ok) throw new Error('Report generation failed')
        return res.text() // The API returns plain text, not JSON.
      })
      .then((text) => setTranscript(text)) // Stores the generated report in state to display in the preview textarea.
      .catch(() => setError(t('share.error')))
      .finally(() => setGenerating(false))
  }, [open, messages, masterprompt]) // Re-runs whenever the modal is opened or the messages change.

  // Called when the user clicks "Send til lærer" — sends the generated report to the teacher via email.
  async function handleSend() {
    setError('')
    setLoading(true)

    try {
      // Posts the report to /api/send-report which forwards it to the teacher's email via Resend.
      const res = await fetch('/api/send-report', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          subject: 'ThinkBot Samtaleeksport',
          body: transcript, // The generated plain-text report.
        }),
      })

      if (!res.ok) throw new Error('Send failed')

      setSent(true) // Shows the "Email sendt" confirmation message.
      // Automatically closes the modal 2 seconds after a successful send.
      setTimeout(() => {
        setOpen(false)
        setSent(false)
      }, 2000)
    } catch {
      setError(t('share.sendError'))
    } finally {
      setLoading(false)
    }
  }

  return (
    <>
      {/* The trigger button shown in the chat header. Disabled if there are no messages yet. */}
      <button
        onClick={() => setOpen(true)}
        disabled={messages.length === 0}
        className="px-4 py-2 rounded-lg text-sm font-medium border border-[var(--border)] text-gray-600 dark:text-gray-400 hover:bg-[var(--bg-panel)] transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
      >
        {t('share.button')}
      </button>

      {/* The share modal — only rendered when open is true. */}
      {open && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40">
          <div className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-xl shadow-xl w-full max-w-2xl mx-4 flex flex-col max-h-[80vh]">
            {/* Modal header with title and close button. */}
            <div className="flex items-center justify-between px-5 py-4 border-b border-[var(--border)]">
              <h2 className="text-lg font-semibold text-gray-800 dark:text-gray-200">
                {t('share.title')}
              </h2>
              <button
                onClick={() => setOpen(false)}
                className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 text-xl leading-none"
              >
                ✕
              </button>
            </div>

            {/* Modal body — shows a spinner while generating, then the report preview textarea. */}
            <div className="flex-1 overflow-hidden px-5 py-4 flex flex-col gap-3">
              <p className="text-sm text-gray-500 dark:text-gray-400">
                {t('share.description')}
              </p>

              {generating ? (
                // Spinning loader shown while the API generates the report.
                <div className="flex-1 flex items-center justify-center py-12">
                  <svg
                    className="animate-spin h-6 w-6 text-gray-400"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                  >
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                  </svg>
                  <span className="ml-3 text-sm text-gray-500">{t('share.generating')}</span>
                </div>
              ) : (
                // Read-only preview of the report text. The student can scroll it but not edit it.
                <textarea
                  value={transcript}
                  readOnly
                  className="flex-1 min-h-[300px] w-full rounded-lg border border-[var(--border)] bg-gray-50 dark:bg-gray-800 text-sm text-gray-800 dark:text-gray-200 p-3 resize-none focus:outline-none cursor-default"
                />
              )}

              {/* Error message shown if generation or sending failed. */}
              {error && (
                <p className="text-sm text-red-500">{error}</p>
              )}

              {/* Success confirmation shown briefly after the email is sent. */}
              {sent && (
                <p className="text-sm text-green-600 dark:text-green-400">
                  {t('share.sent')}
                </p>
              )}
            </div>

            {/* Modal footer with cancel and send buttons. */}
            <div className="flex items-center justify-end gap-3 px-5 py-4 border-t border-[var(--border)]">
              <button
                onClick={() => setOpen(false)}
                className="px-4 py-2 rounded-lg text-sm font-medium border border-[var(--border)] text-gray-600 dark:text-gray-400 hover:bg-[var(--bg-panel)] transition-colors"
              >
                {t('share.cancel')}
              </button>
              {/* Send button — disabled while generating, loading, if there's nothing to send, or after a successful send. */}
              <button
                onClick={handleSend}
                disabled={loading || generating || !transcript.trim() || sent}
                className="px-4 py-2 rounded-lg text-sm font-medium bg-blue-600 text-white hover:bg-blue-700 transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
              >
                {loading ? (
                  // Shows a spinner and "Sender…" text while the email request is in flight.
                  <span className="flex items-center gap-2">
                    <svg
                      className="animate-spin h-3.5 w-3.5"
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                    >
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                    </svg>
                    {t('share.sending')}
                  </span>
                ) : (
                  t('share.sendButton')
                )}
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  )
}
